platform :ios, '8.0'
workspace 'Demo-iOS.xcworkspace'

# 自己整合的第三方类库
pod 'ThirdParty', :git => 'https://github.com/mrhuangyuhui/repo-third-party-ios.git'

# 其他第三方类库
pod 'Masonry', :git => 'https://github.com/cloudkite/Masonry.git'
pod 'BlocksKit', :git => 'https://github.com/zwaldowski/BlocksKit.git'
pod 'YYKit', :git => 'https://github.com/ibireme/YYKit.git'

target "Demo-iOS" do
  project "Demo-iOS/Demo-iOS.xcodeproj"
end

target "YYKitDemo" do
    project "YYKitDemo/YYKitDemo.xcodeproj"
end
